export enum EPath {
  PERSONAL_INFO = 'PERSONAL_INFO',
  MAIN = 'MAIN',
  PROFILE = 'PROFILE',
  GROUP = 'GROUP',
  EMPLOYEE_RELATED_INFO = 'EMPLOYEE_RELATED_INFO ',
  REGISTRATION_FLOW = 'REGISTRATION_FLOW',
  AUTH_USER = 'AUTH_USER',
}
